### ISSUE TITLE
wrong score?

### ISSUE THREAD

**Issue by nicolabertoldi** [rwth-i6/CharacTER#1]
considering this sentence "alpha beta" for both hyp and ref
I correctly get the characTER score of 0.0

BUT

considering this sentence "alpha alpha" for both hyp and ref
I get the characTER score of 0.4.

Is there any reason for that?
Is it a bug?

**Comment by Nintendo-Wei** [comment]
Hi,

It is a bug. Thanks for reporting this. We will fix it and update the code soon.

BR
Weiyue

**Comment by Nintendo-Wei** [comment]
Hi,

The bug is fixed. It is mainly due to costs created by some not appropriate shifts. Now it should be fine.

Many thanks again.
Weiyue
